const express = require("express");
const cron = require("node-cron");
const cors = require('cors')
const app = express();
const port = 3000;

app.use(cors());

// Define the array of quotes for the day
const quotesOfTheDay = [
  "Embrace the journey, for every step forward is progress.",
  "Today is a new opportunity to create something amazing.",
  "Let your actions speak louder than your words.",
  "Believe in yourself, for you are capable of greatness.",
  "Find joy in the little things today.",
  "Challenge yourself to step out of your comfort zone.",
  "Remember to be kind to yourself and others.",
  "See the beauty in every moment.",
  "Success comes to those who persist in their efforts.",
  "Live each day with purpose and passion.",
  "Focus on progress, not perfection.",
  "Be the reason someone smiles today.",
  "Take a moment to appreciate how far you've come.",
  "Choose positivity and watch your world transform.",
  "Every setback is a setup for a comeback.",
  "Find strength in adversity and keep moving forward.",
  "Celebrate your victories, no matter how small.",
  "Stay true to your values and beliefs.",
  "Trust in the journey, even when the path is unclear.",
  "The only way to fail is to stop trying.",
  "Spread love and kindness wherever you go.",
  "Stay focused on your goals and ignore the distractions.",
  "Be grateful for the blessings in your life.",
  "Dream big and work hard to make it a reality.",
  "Take the first step, even if it's the hardest.",
  "Let go of what you can't control and focus on what you can.",
  "Life is what you make it, so make it amazing.",
  "Stay humble, stay hungry, and keep hustling.",
  "You are stronger than you think, braver than you believe, and smarter than you know.",
  "Today is a gift, that's why they call it the present.",
  "Focus on the present moment and make it count.",
  "Be the change you wish to see in the world.",
  "Your attitude determines your direction.",
  "Success is not final, failure is not fatal: It's the courage to continue that counts.",
  "Take a deep breath and trust the process.",
  "Every day is a second chance to get it right.",
  "The best way to predict the future is to create it.",
  "Find joy in the journey, not just the destination.",
  "Life is too short to waste on negativity.",
  "Remember, you are capable of amazing things.",
  "Don't be afraid to fail, be afraid not to try.",
  "Live in the moment and make it beautiful.",
  "Believe in yourself and all that you are.",
  "Success is not measured by what you accomplish, but by the obstacles you overcome.",
  "Find strength in your struggles and courage in your fears.",
  "Today is the perfect day to start living your dreams.",
  "Chase your dreams with all your heart.",
  "The secret of getting ahead is getting started.",
  "Don't let fear hold you back from reaching your full potential.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Focus on progress, not perfection.",
  "The best way to predict the future is to create it.",
  "Your time is now. Seize the moment and make it count.",
  "Believe in yourself and all that you are capable of.",
  "You are stronger than you think, braver than you believe, and smarter than you know.",
  "Stay focused, stay positive, and keep moving forward.",
  "Every day is a new beginning, take a deep breath and start again.",
  "Don't let the opinions of others define you. Believe in yourself and follow your own path.",
  "Be kind, be brave, be yourself.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Embrace the challenges that come your way, for they will only make you stronger.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Find joy in the journey, not just the destination.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Stay true to yourself and never compromise your values.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
  "Be the change you wish to see in the world.",
  "Every day is a new opportunity to learn and grow.",
  "Stay positive, stay focused, and stay determined.",
  "Believe in yourself, even when no one else does.",
  "Success is not defined by your past, but by your future.",
  "The only way to fail is to never try.",
  "Be kind, be brave, and be yourself.",
  "Life is too short to waste on negativity. Focus on the positive and make the most of every moment.",
  "Take risks, make mistakes, and learn from them. That's how you grow.",
  "Stay true to yourself and never compromise your values.",
  "Be the change you wish to see in the world.",
  "Don't be afraid to stand out from the crowd and be different. That's what makes you unique.",
  "Believe in yourself and all that you are capable of achieving.",
  "The only way to do great work is to love what you do.",
  "Success is not measured by the size of your bank account, but by the impact you have on others.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Be the reason someone smiles today.",
  "Life is a journey, not a destination. Enjoy the ride.",
  "Never underestimate the power of kindness and compassion.",
  "Take a moment to appreciate how far you've come and how much you've achieved.",
  "Believe in yourself and all that you are capable of.",
  "Stay true to your values and never compromise your integrity.",
  "Success is not about how much money you make, but how many lives you touch.",
  "Focus on progress, not perfection.",
  "Dream big, work hard, and never give up on your dreams.",
];

let quoteOfTheDay = getRandomItem(quotesOfTheDay);

function getRandomItem(array) {
  return array[Math.floor(Math.random() * array.length)];
}

// Set up a cron job to update the quote of the day at midnight
cron.schedule("0 0 * * *", () => {
  quoteOfTheDay = getRandomItem(quotesOfTheDay);
  console.log("Quote of the day updated:", quoteOfTheDay);
});

// Endpoint to get the current quote of the day
app.get("/", (req, res) => {
  res.json({ QuotesofTheDay: quoteOfTheDay });
});

app.listen(port, () => {
  console.log(`Server is running at http://localhost:${port}/`);
});
